# Generated by Django 3.1.7 on 2021-04-23 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256)),
                ('lastnames', models.CharField(max_length=256)),
                ('id_number', models.CharField(max_length=128)),
                ('contactNumber', models.CharField(max_length=128)),
            ],
        ),
    ]
