# Generated by Django 3.1.7 on 2021-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4hPatients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactNumber',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
